-- MySQL Script generated by MySQL Workbench
-- Thu Mar  4 14:13:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Agenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agenda` DEFAULT CHARACTER SET utf8 ;
USE `Agenda` ;

-- -----------------------------------------------------
-- Table `Agenda`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agenda`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agenda`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agenda`.`Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  INDEX `fk_Telefono_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Agenda`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agenda`.`Correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agenda`.`Correo` (
  `idCorreo` INT NOT NULL AUTO_INCREMENT,
  `Correo` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idCorreo`),
  INDEX `fk_Correo_Persona_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Correo_Persona`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Agenda`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `inventario`.`Persona`
-- -----------------------------------------------------
START TRANSACTION;
USE `Agenda`;
INSERT INTO `Agenda`.`Persona` (`nombre`) VALUES ('Angel');
INSERT INTO `Agenda`.`Persona` (`nombre`) VALUES ('Mario');
INSERT INTO `Agenda`.`Persona` (`nombre`) VALUES ('Carlos');
INSERT INTO `Agenda`.`Persona` (`nombre`) VALUES ('Sandra');
INSERT INTO `Agenda`.`Persona` (`nombre`) VALUES ('Laura');
INSERT INTO `Agenda`.`Persona` (`nombre`) VALUES ('Zaira');

COMMIT;

-- -----------------------------------------------------
-- Data for table `inventario`.`Telefono`
-- -----------------------------------------------------
START TRANSACTION;
USE `Agenda`;
INSERT INTO `Agenda`.`Telefono` (`numero`,`Persona_idPersona`) VALUES ('2281819155', '1');
INSERT INTO `Agenda`.`Telefono` (`numero`,`Persona_idPersona`) VALUES ('2281915584', '2');
INSERT INTO `Agenda`.`Telefono` (`numero`,`Persona_idPersona`) VALUES ('2281365978', '3');
INSERT INTO `Agenda`.`Telefono` (`numero`,`Persona_idPersona`) VALUES ('2282456785', '4');
INSERT INTO `Agenda`.`Telefono` (`numero`,`Persona_idPersona`) VALUES ('1258745668', '5');
INSERT INTO `Agenda`.`Telefono` (`numero`,`Persona_idPersona`) VALUES ('2286597845', '6');

COMMIT;

-- -----------------------------------------------------
-- Data for table `inventario`.`Correo`
-- -----------------------------------------------------
START TRANSACTION;
USE `Agenda`;
INSERT INTO `Agenda`.`Correo` (`Correo`,`Persona_idPersona`) VALUES ('Angel254978@hotmail.com', '1');
INSERT INTO `Agenda`.`Correo` (`Correo`,`Persona_idPersona`) VALUES ('Mario215462@hotmail.com', '2');
INSERT INTO `Agenda`.`Correo` (`Correo`,`Persona_idPersona`) VALUES ('Carlos54954@hotmail.com', '3');
INSERT INTO `Agenda`.`Correo` (`Correo`,`Persona_idPersona`) VALUES ('Sandra54655@hotmail.com', '4');
INSERT INTO `Agenda`.`Correo` (`Correo`,`Persona_idPersona`) VALUES ('Laura456456@hotmail.com', '5');
INSERT INTO `Agenda`.`Correo` (`Correo`,`Persona_idPersona`) VALUES ('Zaira456468@hotmail.com', '6');

COMMIT;

-- SET SQL_MODE = '';
-- DROP USER IF EXISTS admin;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'admin' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;