version: '3.9'

services:
    bd-agenda:
        image: mysql/mysql-server:latest
        container_name: contenedor-bd
        ports:
            - "8080:3306"
        restart: always
        volumes:
            - volumen-agenda:/var/lib/mysql
            - ./bd/agenda.sql:/docker-entrypoint-initdb.d/agenda.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "Agenda"
            MYSQL_USER: "root"
        
    app-agenda:
        image: app-agenda
        container_name: contenedor-agenda
        build:
            context: ./agenda/
            dockerfile: Dockerfile
        stdin_open: true 
        tty: true       
        depends_on: 
            - "bd-agenda"
        environment: 
            DB_CONNECTION_STRING: "server=bd-agenda;user=admin;password=admin;database=Agenda"
volumes:
    volumen-agenda: